FROM ft-rails:on-build

EXPOSE 3000
CMD [ "rails" , "s", "-b", "0.0.0.0", "-p", "3000"]

# How to build it?
# docker build -t r1-image .

# How to run it?
# docker run --name r1-container -it --rm -p 3000:3000 r1-image
